config/routes.rb
Rails.application.routes.draw do

  root :to => 'public#index'

  get 'show/:title', :to => 'public#show', :as => 'public_show'

  devise_for :users
  # resources :users, only: [:index, :show]

  resources :charges

  #resourceful routes
  resources :meetings do
    member do
      get :delete
    end
  end

  # resources :users do
  #   member do
  #     get :delete
  #   end
  # end

  resources :affiliates do
    member do
      get :delete
    end
  end

  resources :attendances do
    member do
      get :delete
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/meeting.rb
class Meeting < ApplicationRecord

	acts_as_votable

	belongs_to :affiliate
	has_many :attendances
	has_many :students, through: :attendances

	scope :visible, lambda { where(:visible => true) }
	scope :invisible, lambda { where(:visible => false) }
	scope :sorted, lambda { order("title ASC") }
	scope :newest_first, lambda { order("created_at DESC") }

	FORBIDDEN_TITLES = ['fuck', 'cunt']

  validates :title, :presence => true,
									:length => {:maximum => 50},
									:uniqueness => true
	validate :title_is_allowed
  validates_presence_of :blurb

	private

	def title_is_allowed
		if FORBIDDEN_TITLES.include?(title)
			errors.add(:title, "has been restricted from use.")
		end
	end

end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController

  before_action(:find_affiliate, {only: [:index, :new, :create]})

  def index
    @meetings = @affiliate.meetings.sorted
  end

  def show
    @meeting = Meeting.find(params[:id])
  end

  def new
    @meeting = Meeting.new(:affiliate_id => @affiliate.id)
  end

  def create
    @meeting = Meeting.new(meeting_params)
    @meeting.affiliate_id = @affiliate.id
    if @meeting.save
      redirect_to(meetings_path(@affiliate))
    else
      render :new
    end
  end

  def edit
    @meeting = Meeting.find(params[:id])
  end

  def update
    @meeting = Meeting.find(params[:id])
    if @meeting.update_attributes(meeting_params)
      redirect_to(meetings_path(@meeting))
    else
      render('edit')
    end
  end

  def delete
    @meeting = Meeting.find(params[:id])
  end

  def destroy
    @meeting = Meeting.find(params[:id])
    @meeting.destroy
    redirect_to(meetings_path)
  end

  private

  def meeting_params
    params.require(:meeting).permit(
      :affiliate_id,
      :title,
      :blurb,
      :address,
      :suburb,
      :postcode)
  end

  def find_affiliate
    @affiliate = Affiliate.find(params[:affiliate_id])
  end

end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/views/meetings/_form.html.erb
<%= error_messages_for(f.object) %>

<table summary="Meeting form fields">
  <tr>
    <th>Affiliate</th>
    <td><%= f.object.affiliate.title %></td>
  </tr>
  <tr>
    <th>Title</th>
    <td><%= f.text_field(:title) %></td>
  </tr>
  <tr>
    <th>Blurb</th>
    <td><%= f.text_area(:blurb, :size => '40x10') %></td>
  </tr>
  <tr>
    <th>Address</th>
    <td><%= f.text_field(:address) %></td>
  </tr>
  <tr>
    <th>Suburb</th>
    <td><%= f.text_field(:suburb) %></td>
  </tr>
  <tr>
    <th>Postcode</th>
    <td><%= f.text_field(:postcode) %></td>
  </tr>
</table>

app/views/meetings/delete.html.erb
<% @page_title = "Delete Meeting" %>

<%= link_to("<< Back to List", meetings_path(:affiliate_id => @affiliate.id), :class => 'back-link') %>

<div class="meetings delete">
  <h2>Delete Meeting</h2>

  <%= form_for(@meeting, :url => meeting_path, :method => 'delete') do |f| %>

    <p>Are you sure you want to permanently delete this meeting?</p>

    <p class="reference-name"><%= f.object.title %></p>

    <div class="form-buttons">
      <%= f.submit("Delete Meeting") %>
    </div>

  <% end %>
</div>

app/views/meetings/edit.html.erb
<% @page_title = "Update Meeting" %>

<%= link_to("<< Back to List", meetings_path(:affiliate_id => @affiliate.id), :class => 'back-link') %>

<div class="meetings edit">
  <h2>Update Meeting</h2>

  <%= form_for(@meeting) do |f| %>

    <%= render(:partial => 'form', :locals => {:f => f}) %>

    <div class="form-buttons">
      <%= f.submit("Update Meeting") %>
    </div>

  <% end %>
</div>

app/views/meetings/index.html.erb
<% @page_title = "All Meetings" %>

<%= link_to("<< Back to Affiliates Menu", affiliates_path, :class => 'back-link') %>

<div class ="meetings index">  <!-- controller and action, CSS easier -->
	<h2>Meetings</h2>

	<%= image_tag('plus_sign.png', :size => '11x11', :alt => '+') %>
	<%= link_to("Add New Meeting", new_meeting_path(:affiliate_id => @affiliate.id), :class => 'action new') %>

	<table class ="listing" summary="Meetings list">
		<tr class="header">
			<th>Title</th>
			<th>Blurb</th>
			<th>Actions</th>
		</tr>
		<% @meetings.each do |meeting| %>
			<tr>
				<td class="center"><%= meeting.title %></td>
				<td class="center"><%= meeting.blurb %></td>
				<td class="actions">
					<%= link_to("Show", meeting_path(meeting, :affiliate_id => @affiliate.id), :class => 'action show') %>
					<%= link_to("Edit", edit_meeting_path(meeting, :affiliate_id => @affiliate.id), :class => 'action edit') %>
					<%= link_to("Delete", delete_meeting_path(meeting, :affiliate_id => @affiliate.id), :class => 'action delete') %>
				</td>
			</tr>
		<% end %>
	</table>
</div>

app/views/meetings/new.html.erb
<% @page_title = "Create Meeting" %>

<%= link_to("<< Back to List", meetings_path, :class => 'back-link') %>

<div class="meeetings new">
  <h2>Create Meeting</h2>

	<%= form_for(@meeting) do |f| %>

    <%= render(:partial => 'form', :locals => {:f => f}) %>

    <div class="form-buttons">
      <%= f.submit("Create Meeting") %>
    </div>

  <% end %>
</div>

app/views/meetings/show.html.erb
<% @page_title = "Display Meeting" %>

<%= link_to("<< Back to Meetings List", meetings_path(:affiliate_id => @affiliate.id), :class => 'back-link') %>

<div class="meetings show">
  <h2>Show Meeting</h2>

  <table summary="Meeting detail view">
    <tr>
      <th>Title</th>
      <td><%= @meeting.title %></td>
    </tr>
    <tr>
      <th>Blurb</th>
      <td><%= @meeting.blurb %></td>
    </tr>
    <tr>
    <tr>
      <th>Address</th>
      <td><%= @meeting.address %></td>
    </tr>
    <tr>
      <th>Suburb</th>
      <td><%= @meeting.suburb %></td>
    </tr>
    <tr>
      <th>Postcode</th>
      <td><%= @meeting.postcode %></td>
    </tr>
  </table>

</div>