config/routes.rb
Rails.application.routes.draw do

  root :to => 'public#index'

  get 'show/:title', :to => 'public#show', :as => 'public_show'

  devise_for :users
  # resources :users, only: [:index, :show]

  resources :charges

  #resourceful routes
  resources :meetings do
    member do
      get :delete
    end
  end

  # resources :users do
  #   member do
  #     get :delete
  #   end
  # end

  resources :affiliates do
    member do
      get :delete
    end
  end

  resources :attendances do
    member do
      get :delete
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

	has_many :affiliates
	has_many :attendances
	has_many :meetings, through: :attendances

	has_attached_file :avatar, styles: { thumb: "100x100#" }
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

	scope :visible, lambda { where(:visible => true) }
	scope :invisible, lambda { where(:visible => false) }
	scope :sorted, lambda { order("username ASC") }
	scope :newest_first, lambda { order("created_at DESC") }
	scope :search, lambda {|query| where(["username LIKE ?", "%#{query}%"]) }

	EMAIL_REGEX = /\A[a-z0-9.%+-]+@[a-z0-9.-]+\.[a-z]{2,4}\Z/i

	validates :first_name, :presence => true,
													:length => {:maximum => 25}
	validates :last_name, :presence => true,
												:length => {:maximum => 50}
	validates :phone_number, :presence => true,
													:length => {:within => 8..20}
	validates :email, :presence => true,
										:length => {:maximum => 100},
										:format => EMAIL_REGEX,
										:confirmation => true
	validates :username, :length => {:within => 6..25},
											:uniqueness => true
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def search
    if params[:search].present?
      @users = User.search(params[:search])
    else
      @users = User.all
    end
  end

  def index
    @users = User.sorted
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to(users_path)
    else
      render('new')
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to(user_path(@user))
    else
      render('edit')
    end
  end

  def delete
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to(affiliates_path)
  end

  private

  def user_params
    params.require(:user).permit(
      :first_name,
      :last_name,
      :phone_number,
      :email,
      :username,
      :password,
      :avatar)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= error_messages_for(f.object) %>

<%= form_for(@user) do |f| %>

  <table summary="User form fields">
    <tr>
      <th>Avatar</th>
      <td><%= f.file_field(:avatar) %></td>
    </tr>
    <tr>
      <th>First Name</th>
      <td><%= f.text_field(:first_name) %></td>
    </tr>
    <tr>
      <th>Last Name</th>
      <td><%= f.text_field(:last_name) %></td>
    </tr>
    <tr>
      <th>Phone Number</th>
      <td><%= f.text_field(:phone_number) %></td>
    </tr>
    <tr>
      <th>Email</th>
      <td><%= f.text_field(:email) %></td>
    </tr>
    <tr>
      <th>Username</th>
      <td><%= f.text_field(:username) %></td>
    </tr>
    <tr>
      <th>Password</th>
      <td><%= f.text_field(:password) %></td>
    </tr>
  </table>
<% end %>

app/views/users/delete.html.erb
<% @page_title = "Delete User" %>

<%= link_to("<< Back to List", users_path, :class => 'back-link') %>

<div class="users delete">
  <h2>Delete User</h2>

  <%= form_for(@user, :url => user_path, :method => 'delete') do |f| %>

    <p>Are you sure you want to permanently delete this user?</p>

    <p class="reference-name"><%= f.object.username %></p>

    <div class="form-buttons">
      <%= f.submit("Delete User") %>
    </div>

  <% end %>
</div>

app/views/users/edit.html.erb
<% @page_title = "Update User" %>

<%= link_to("<< Back to List", users_path, :class => 'back-link') %>

<div class="users edit">
  <h2>Update User</h2>

  <%= form_for(@user) do |f| %>

  	<%= render(:partial => 'form', :locals => {:f => f}) %>

	  <div class="form-buttons">
	    <%= f.submit("Update User") %>
	  </div>

  <% end %>
</div>

app/views/users/index.html.erb
<% @page_title = "All Users" %>

<%= link_to("<< Back to Menu", users_path, :class => 'back-link') %>

<div class ="users index">  <!-- controller and action, CSS easier -->
	<h2>Students</h2>

	<%= image_tag('plus_sign.png', :size => '11x11', :alt => '+') %>
	<%= link_to("Add New User", new_user_path, :class => 'action new') %>

	<table class ="listing" summary="Users list">
		<tr class="header">
			<th>Avatar</th>
			<th>First Name</th>
			<th>Last Name</th>
			<th>Number of Affiliates</th>
			<th>Actions</th>
		</tr>
		<% @users.each do |user| %>
			<tr>
				<td><%= image_tag user.avatar.url(:thumb) %></td>
				<td><%= user.first_name %></td>
				<td><%= user.last_name %></td>
				<td><%= user.affiliates.size %></td>
				<td class="actions">
					<%= link_to("View Affiliates", affiliates_path, :class => 'action show') %>
					<%= link_to("Show", user_path(user), :class => 'action show') %>
					<%= link_to("Edit", edit_user_path(user), :class => 'action edit') %>
					<%= link_to("Delete", delete_user_path(user), :class => 'action delete') %>
				</td>
			</tr>
		<% end %>
	</table>
</div>

app/views/users/new.html.erb
<% @page_title = "Create User" %>

<%= link_to("<< Back to List", users_path, :class => 'back-link') %>

<div class="users new">
  <h2>Create User</h2>

  <%= form_for(@user) do |f| %>

    <%= render(:partial => 'form', :locals => {:f => f}) %>

    <div class="form-buttons">
      <%= f.submit("Create User") %>
    </div>

  <% end %>
</div>

app/views/users/show.html.erb
<% @page_title = "Display User" %>

<%= link_to("<< Back to Users List", users_path, :class => 'back-link') %>

<div class="users show">
  <h2>Show User</h2>

  <table summary="User detail view">
    <tr>
      <th>Avatar</th>
      <td><%= image_tag @user.avatar.url(:thumbnail) %></td>
    </tr>
    <tr>
      <th>First Name</th>
      <td><%= @user.first_name %></td>
    </tr>
    <tr>
      <th>Last Name</th>
      <td><%= @user.last_name %></td>
    </tr>
    <tr>
      <th>Phone Number</th>
      <td><%= @user.phone_number %></td>
    </tr>
    <tr>
      <th>Email</th>
      <td><%= @user.email %></td>
    </tr>
    <tr>
      <th>Username</th>
      <td><%= @user.username %></td>
    </tr>
    <tr>
      <th>Password</th>
      <td><%= @user.password %></td>
    </tr>
  </table>

</div>