config/routes.rb
Rails.application.routes.draw do

  root :to => 'public#index'

  get 'show/:title', :to => 'public#show', :as => 'public_show'

  devise_for :users
  # resources :users, only: [:index, :show]

  resources :charges

  #resourceful routes
  resources :meetings do
    member do
      get :delete
    end
  end

  # resources :users do
  #   member do
  #     get :delete
  #   end
  # end

  resources :affiliates do
    member do
      get :delete
    end
  end

  resources :attendances do
    member do
      get :delete
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/affiliate.rb
class Affiliate < ApplicationRecord

	has_many :meetings
	belongs_to :user

	default_scope lambda { order("title ASC") }
	scope :newest_first, lambda { order("created_at DESC") }
	scope :search, lambda {|query| where(["title LIKE ?", "%#{query}%"]) }

	EMAIL_REGEX = /\A[a-z0-9.%+-]+@[a-z0-9.-]+\.[a-z]{2,4}\Z/i
	FORBIDDEN_TITLES = ['fuck', 'cunt']

	validates :title, :presence => true,
									:length => {:maximum => 50},
									:uniqueness => true
	validate :title_is_allowed
	validates :phone_number, :presence => true,
													:length => {:within => 8..20}
	validates :email, :presence => true,
										:length => {:maximum => 100},
										:format => EMAIL_REGEX,
										:confirmation => true
	validates :suburb, :length => {:maximum => 20}
	validates :annual_fee, :presence => true
	validates_presence_of :category

	private

	def title_is_allowed
		if FORBIDDEN_TITLES.include?(title)
			errors.add(:title, "has been restricted from use.")
		end
	end

end

app/controllers/affiliates_controller.rb
class AffiliatesController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show]
  # before_action :find_student

  def search
    if params[:search].present?
      @affiliates = Affiliate.search(params[:search])
    else
      @affiliates = Affiliate.all
    end
  end

  def index
    @affiliates = Affiliate.all
  end

  def show
    @affiliate = Affiliate.find(params[:id])
  end

  def new
    @affiliate = current_user.affiliates.build
  end

  def create
    @affiliate = current_user.affiliates.build(affiliate_params)
    @affiliate.user = current_user
    if @affiliate.save
      redirect_to(affiliates_path)
    else
      render('new')
    end
  end

  def edit
    @affiliate = Affiliate.find(params[:id])
  end

  def update
    @affiliate = Affiliate.find(params[:id])
    if @affiliate.update_attributes(affiliate_params)
      redirect_to(affiliate_path(@affiliate))
    else
      render('edit')
    end
  end

  def delete
    @affiliate = Affiliate.find(params[:id])
  end

  def destroy
    @affiliate = Affiliate.find(params[:id])
    @affiliate.destroy
    redirect_to(affiliates_path)
  end

  private

  def affiliate_params
    params.require(:affiliate).permit(
      :title,
      :about,
      :phone_number,
      :email,
      :address,
      :suburb,
      :postcode,
      :annual_fee,
      :category,
      :user_id)
  end

end

app/helpers/affiliates_helper.rb
module AffiliatesHelper
end

app/views/affiliates/_form.html.erb
<%= error_messages_for(f.object) %>

  <table summary="Affiliate form fields">
    <tr>
      <th>Title</th>
      <td><%= f.text_field(:title) %></td>
    </tr>
    <tr>
      <th>About</th>
      <td><%= f.text_area(:about, :size => '40x10') %></td>
    </tr>
    <tr>
      <th>Phone Number</th>
      <td><%= f.text_field(:phone_number) %></td>
    </tr>
    <tr>
      <th>Email</th>
      <td><%= f.text_field(:email) %></td>
    </tr>
    <tr>
      <th>Address</th>
      <td><%= f.text_field(:address) %></td>
    </tr>
    <tr>
      <th>Suburb</th>
      <td><%= f.text_field(:suburb) %></td>
    </tr>
    <tr>
      <th>Postcode</th>
      <td><%= f.text_field(:postcode) %></td>
    </tr>
    <tr>
      <th>Annual Fee</th>
      <td><%= f.text_field(:annual_fee) %></td>
    </tr>
    <tr>
      <th>Category</th>
      <td><%= f.select(:category, %w{ Academic Creatives Cuisine Cultural Languages Spiritual Social Sports }) %></td>
    </tr>
  </table>

app/views/affiliates/_public.html.erb
<table class ="listing" summary="Affiliates list">
  <tr class="header">
    <th>Alphabetical</th>
  </tr>
  <% affiliates.each do |affiliate| %>
    <tr>
      <td><%= link_to("#{affiliate.title}", affiliate_path(affiliate), :class => 'action show_public') %></td>
    </tr>
  <% end %>
</table>

app/views/affiliates/delete.html.erb
<% @page_title = "Delete Affiliate" %>

<%= link_to("<< Back to List", affiliates_path, :class => 'back-link') %>

<div class="affiliates delete">
  <h2>Delete Affiliate</h2>

  <%= form_for(@affiliate, :url => affiliate_path, :method => 'delete') do |f| %>

    <p>Are you sure you want to permanently delete this affiliate?</p>

    <p class="reference-name"><%= f.object.title %></p>

    <div class="form-buttons">
      <%= f.submit("Delete Affiliate") %>
    </div>

  <% end %>
</div>

app/views/affiliates/edit.html.erb
<% @page_title = "Update Affiliate" %>

<%= link_to("<< Back to List", affiliates_path, :class => 'back-link') %>

<div class="affiliates edit">
  <h2>Update Affiliate</h2>

	<%= form_for(@affiliate) do |f| %>

    <%= render(:partial => 'form', :locals => {:f => f}) %>

    <div class="form-buttons">
      <%= f.submit("Update Affiliate") %>
    </div>
    
  <% end %>
</div>

app/views/affiliates/index.html.erb
<% @page_title = "All Affiliates" %>

<%= link_to("<< Back to Users Menu", users_path, :class => 'back-link') %>

<div class ="affiliates index">  <!-- controller and action, CSS easier -->
	<h2>Affiliates</h2>

	<%= image_tag('plus_sign.png', :size => '11x11', :alt => '+') %>
	<%= link_to("Add New Affiliate", new_affiliate_path, :class => 'action new') %>

	<table class ="listing" summary="Affiliates list">
		<tr class="header">
			<th>Title</th>
			<th>About</th>
			<th>Actions</th>
		</tr>
		<% @affiliates.each do |affiliate| %>
			<tr>
				<td><%= affiliate.title %></td>
				<td><%= affiliate.about %></td>
				<td class="actions">
					<%= link_to("View Meetings", meetings_path(:affiliate_id => affiliate.id), :class => 'action show') %>
					<%= link_to("Show", affiliate_path(affiliate), :class => 'action show') %>
					<%= link_to("Edit", edit_affiliate_path(affiliate), :class => 'action edit') %>
					<%= link_to("Delete", delete_affiliate_path(affiliate), :class => 'action delete') %>
				</td>
			</tr>
		<% end %>
	</table>
</div>

app/views/affiliates/new.html.erb
<% @page_title = "Create Affiliate" %>

<%= link_to("<< Back to List", affiliates_path, :class => 'back-link') %>

<div class="affiliates new">
  <h2>Create Affiliate</h2>

	<%= form_for(@affiliate) do |f| %>

    <%= render(:partial => 'form', :locals => {:f => f}) %>

    <div class="form-buttons">
      <%= f.submit("Create Affiliate") %>
    </div>

  <% end %>
</div>

app/views/affiliates/search.html.erb
<div class="row">
  <% @affiliates.each do |affiliate| %>
    <div class="col-sm-6 col-md-3">
      <div class="thumbnail">
        <%= link_to (image_tag affiliate.avatar.url(:thumbnail), class: 'image'), affiliate %>
      </div>
    </div>
  <% end %>
</div>

app/views/affiliates/show.html.erb
<% @page_title = "Display Affiliate" %>

<% if user_signed_in? %>
  <%= link_to("<< Back to Homepage", root_path, :class => 'back-link') %>
<% else %>
  <!-- Display nothing -->
<% end %>

<div class="affiliates show">
  <h2>Show Affiliate</h2>

  <table summary="Affiliate detail view">
    <tr>
      <th>Title</th>
      <td><%= @affiliate.title %></td>
    </tr>
    <tr>
      <th>About</th>
      <td><%= @affiliate.about %></td>
    </tr>
    <tr>
      <th>Phone Number</th>
      <td><%= @affiliate.phone_number %></td>
    </tr>
    <tr>
      <th>Email</th>
      <td><%= @affiliate.email %></td>
    </tr>
    <tr>
      <th>Address</th>
      <td><%= @affiliate.address %></td>
    </tr>
    <tr>
      <th>Suburb</th>
      <td><%= @affiliate.suburb %></td>
    </tr>
    <tr>
      <th>Postcode</th>
      <td><%= @affiliate.postcode %></td>
    </tr>
    <tr>
      <th>Annual Fee $</th>
      <td><%= @affiliate.annual_fee %></td>
    </tr>
    <tr>
      <th>Category</th>
      <td><%= @affiliate.category %></td>
    </tr>
  </table>

  <h6>Google Map of location</h6>

  <%= link_to "Join", new_user_registration_path, class: "active" %>

</div>